### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by e5c** [jsilve24/stray#22]
Hi! I received this error during installation. My environment is the [rocker/tidyverse](https://hub.docker.com/r/rocker/tidyverse/) docker container.   

```
> devtools::install_github("jsilve24/stray", build_vignettes=TRUE)
Downloading GitHub repo jsilve24/stray@master
Error in info[!to_ignore, ] : incorrect number of dimensions
> devtools::install_github("jsilve24/stray", build_vignettes=TRUE, ref="develop")
Downloading GitHub repo jsilve24/stray@develop
Error in info[!to_ignore, ] : incorrect number of dimensions
```

**Comment by jsilve24** [comment]
Hey, thanks so much for pointing this out! 

This was really weird, somewhere about 2 months ago a empty .gitmodules file got added and that was causing problems in the function update_submodules in the remotes package. 

.gitmodules was deleted and now it should install without problem. Please try it again. 

Closed 6948eb0858611cc6d4c43d6bf45f6d050ab8e869

**Comment by jsilve24** [comment]
P.S. I have just submitted a pull request to the package `remotes` so that install_github is robust to empty .gitmodules files in the future: https://github.com/r-lib/remotes/pull/329

**Comment by e5c** [comment]
Thanks for this and the upstream patch! This install error is indeed fixed; going to create a new issue with another one...
