### ISSUE TITLE
New installation command needed for vignettes in devtools version 2+

### ISSUE THREAD

**Issue by mikemc** [jsilve24/stray#25]
New `devtools` uses `remotes` for `install_github`; the `build_vignettes` argument is not used anymore and instead the `build_opts` option needs to be changed from its default to get vignettes to build. See https://community.rstudio.com/t/vignettes-suddenly-stopped-installing/18391

**Comment by jsilve24** [comment]
Thanks a lot!
8a09c5583e21223419736abb84efb63e0f89950a
