### ISSUE TITLE
Possible to specify sample-specific offsets?

### ISSUE THREAD

**Issue by mikemc** [jsilve24/stray#37]
Hi Justin, are offsets supported in `pibble` models, as typically specified by the `offset` parameter or with `offset()` within a `formula` for variants of linear regression and logistic regression models in R? 

I'd like to use `pibble()` to fit linear models to the (log) protocol efficiency parameters (sensu https://doi.org/10.7554/eLife.46923) from mock community measurements where we know the true taxonomic composition of the sample. By analogy with multinomial logistic regression implementations, it seems like the natural way to do this in a `pibble` model is to specify offsets for the `eta_j` corresponding to the (log) known composition of sample `j`. For example, to do this using multinomial regression with `nnet::multinom()` I can run
```r
fit <- nnet::multinom(observed ~ var1 + var2 - offset(log(actual + 1e-10)), sam)
```
where `observed` is the table of observed counts, `actual` is the table with the true proportions (both with samples as rows and taxa as columns), `sam` is the sample data, and `var1` and `var2` are sample covariates. I've had to add `1e-10` to the true proportions so that there are no 0s, because `multinom()` will fail if there are `-Inf`'s in the offset matrix.

**Comment by jsilve24** [comment]
Good question. stray doesn't support `offset` as you can get the same effect by simply parameterizing your prior with (near) infinite certainty regarding the offset. 

e.g., you could simply add the known offset to the matrix `Theta` and have a corresponding term in `Gamma` that is near zero.

Does that make sense? Will this work for you?

**Comment by mikemc** [comment]
Thanks for the quick reply and suggestion. On the face of it, adding an offset to Theta doesn't seem to give what I want, as I want to specify an offset for each sample (for each of the N eta_j's), whereas Lambda and Theta are (D-1) by Q matrices (if I'm understanding correctly). But I may be able to take this approach if I first introduce a covariate that simply indexes each sample; I'll give it a shot.

**Comment by jsilve24** [comment]
Yup. I would just add N extra covariates and for each make the corresponding entry in Gamma near zero. Based on the way stray is implemented this will often lead to negligible increases in run-time.

**Comment by mikemc** [comment]
I finally got around to getting this to work! So I suppose I might as well close this. I hope to get some worked examples online soon of using pibble models to do the bias + calibration analysis described in https://doi.org/10.7554/eLife.46923 since they seem like a very useful tool for this purpose.
