### ISSUE TITLE
Perhaps you need a new name

### ISSUE THREAD

**Issue by robjhyndman** [jsilve24/stray#41]
There is a stray package on CRAN already: https://cran.r-project.org/package=stray
You might like to think of a different name.

**Comment by jsilve24** [comment]
Wow. 

Our paper had been out for months when yours proposed that name. We have a number of citations using the name stray. 

This is incredibly frustrating.

**Comment by jsilve24** [comment]
https://arxiv.org/abs/1903.11695

**Comment by jsilve24** [comment]
I will admit it looks like your first commit on github was about 4 months before mine. Perhaps I am in the wrong here. I will look into alternative options.

**Comment by robjhyndman** [comment]
Yes, we did do a check on the name at the time using the [`available` package](https://github.com/r-lib/available). It was only when @pridiltal told me yesterday that she had spotted your package on github that I even knew about it. There is also the [`strayr` package](https://github.com/MattCowgill/strayr) which is a play on the name "Australia" with an Australian pronunciation. 

At least github does automatic redirects if you change the name. `mallard` is available and you could do a cute mallard duck hex sticker.

**Comment by jsilve24** [comment]
Development is continuing under the name *fido*

https://github.com/jsilve24/fido
